uploads = []
outputs = []

[[generated]]
id = "q5PUlpKh3MjmIXxWXpNRH"
uri = "file://assets/img/login_new.png"
type = "image"
title = "generated_image"

[[generated]]
id = "38fUiFqGEd0yEp41vvKLk"
uri = "file://assets/img/olvidarpassword_new.png"
type = "image"
title = "generated_image"

[[generated]]
id = "HK2Yvj0HM4-qKbyOebf5M"
uri = "file://assets/img/fachada-clinica.png"
type = "image"
title = "generated_image"
